-- GradeDock complete fresh-project Supabase database + storage setup
-- RUN ONLY ON A BRAND-NEW SUPABASE PROJECT. No old GradeDock account is required.
-- Run the ENTIRE file once in SQL Editor.

BEGIN;
-- GradeDock v2 fresh Supabase setup
-- Run this in the Supabase SQL Editor for a NEW GradeDock project.
-- GradeDock v2 organizes scan results by section/class and does not require student accounts or rosters.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  school_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.classes (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  -- `name` is kept for compatibility. GradeDock v2 stores the section here too.
  name text not null,
  grade_level text,
  section text not null,
  school_year text,
  created_at timestamptz not null default now()
);

create table if not exists public.exams (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  question_count integer not null check (question_count between 5 and 50),
  choice_count integer not null default 4 check (choice_count in (4,5)),
  created_at timestamptz not null default now()
);

create table if not exists public.exam_keys (
  id bigint generated by default as identity primary key,
  exam_id uuid not null references public.exams(id) on delete cascade,
  question_number integer not null,
  correct_answer text not null check (correct_answer in ('A','B','C','D','E')),
  unique (exam_id, question_number)
);

create table if not exists public.results (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  class_id uuid not null references public.classes(id) on delete cascade,
  exam_id uuid not null references public.exams(id) on delete cascade,
  student_name text not null,
  score integer not null,
  total_items integer not null,
  percentage numeric(6,2) not null,
  review_count integer not null default 0,
  scan_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.result_answers (
  id bigint generated by default as identity primary key,
  result_id uuid not null references public.results(id) on delete cascade,
  question_number integer not null,
  student_answer text,
  correct_answer text,
  is_correct boolean not null default false,
  status text not null default 'ok' check (status in ('ok','blank','multiple')),
  unique (result_id, question_number)
);

create index if not exists classes_teacher_idx on public.classes(teacher_id);
create index if not exists exams_teacher_idx on public.exams(teacher_id);
create index if not exists exam_keys_exam_idx on public.exam_keys(exam_id);
create index if not exists results_teacher_idx on public.results(teacher_id);
create index if not exists results_class_idx on public.results(class_id);
create index if not exists results_exam_idx on public.results(exam_id);
create index if not exists result_answers_result_idx on public.result_answers(result_id);

alter table public.profiles enable row level security;
alter table public.classes enable row level security;
alter table public.exams enable row level security;
alter table public.exam_keys enable row level security;
alter table public.results enable row level security;
alter table public.result_answers enable row level security;

-- Make this setup safe to rerun.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "classes_select_own" on public.classes;
drop policy if exists "classes_insert_own" on public.classes;
drop policy if exists "classes_update_own" on public.classes;
drop policy if exists "classes_delete_own" on public.classes;
drop policy if exists "exams_select_own" on public.exams;
drop policy if exists "exams_insert_own" on public.exams;
drop policy if exists "exams_update_own" on public.exams;
drop policy if exists "exams_delete_own" on public.exams;
drop policy if exists "exam_keys_select_owned_exam" on public.exam_keys;
drop policy if exists "exam_keys_insert_owned_exam" on public.exam_keys;
drop policy if exists "exam_keys_update_owned_exam" on public.exam_keys;
drop policy if exists "exam_keys_delete_owned_exam" on public.exam_keys;
drop policy if exists "results_select_own" on public.results;
drop policy if exists "results_insert_own" on public.results;
drop policy if exists "results_update_own" on public.results;
drop policy if exists "results_delete_own" on public.results;
drop policy if exists "result_answers_select_owned_result" on public.result_answers;
drop policy if exists "result_answers_insert_owned_result" on public.result_answers;
drop policy if exists "result_answers_update_owned_result" on public.result_answers;
drop policy if exists "result_answers_delete_owned_result" on public.result_answers;

create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "classes_select_own" on public.classes for select to authenticated using ((select auth.uid()) = teacher_id);
create policy "classes_insert_own" on public.classes for insert to authenticated with check ((select auth.uid()) = teacher_id);
create policy "classes_update_own" on public.classes for update to authenticated using ((select auth.uid()) = teacher_id) with check ((select auth.uid()) = teacher_id);
create policy "classes_delete_own" on public.classes for delete to authenticated using ((select auth.uid()) = teacher_id);

create policy "exams_select_own" on public.exams for select to authenticated using ((select auth.uid()) = teacher_id);
create policy "exams_insert_own" on public.exams for insert to authenticated with check ((select auth.uid()) = teacher_id);
create policy "exams_update_own" on public.exams for update to authenticated using ((select auth.uid()) = teacher_id) with check ((select auth.uid()) = teacher_id);
create policy "exams_delete_own" on public.exams for delete to authenticated using ((select auth.uid()) = teacher_id);

create policy "exam_keys_select_owned_exam" on public.exam_keys for select to authenticated
using (exists (select 1 from public.exams e where e.id = exam_keys.exam_id and e.teacher_id = (select auth.uid())));
create policy "exam_keys_insert_owned_exam" on public.exam_keys for insert to authenticated
with check (exists (select 1 from public.exams e where e.id = exam_keys.exam_id and e.teacher_id = (select auth.uid())));
create policy "exam_keys_update_owned_exam" on public.exam_keys for update to authenticated
using (exists (select 1 from public.exams e where e.id = exam_keys.exam_id and e.teacher_id = (select auth.uid())))
with check (exists (select 1 from public.exams e where e.id = exam_keys.exam_id and e.teacher_id = (select auth.uid())));
create policy "exam_keys_delete_owned_exam" on public.exam_keys for delete to authenticated
using (exists (select 1 from public.exams e where e.id = exam_keys.exam_id and e.teacher_id = (select auth.uid())));

create policy "results_select_own" on public.results for select to authenticated
using ((select auth.uid()) = teacher_id);
create policy "results_insert_own" on public.results for insert to authenticated
with check (
  (select auth.uid()) = teacher_id
  and exists (select 1 from public.exams e where e.id = results.exam_id and e.teacher_id = (select auth.uid()))
  and exists (select 1 from public.classes c where c.id = results.class_id and c.teacher_id = (select auth.uid()))
);
create policy "results_update_own" on public.results for update to authenticated
using ((select auth.uid()) = teacher_id)
with check (
  (select auth.uid()) = teacher_id
  and exists (select 1 from public.exams e where e.id = results.exam_id and e.teacher_id = (select auth.uid()))
  and exists (select 1 from public.classes c where c.id = results.class_id and c.teacher_id = (select auth.uid()))
);
create policy "results_delete_own" on public.results for delete to authenticated
using ((select auth.uid()) = teacher_id);

create policy "result_answers_select_owned_result" on public.result_answers for select to authenticated
using (exists (select 1 from public.results r where r.id = result_answers.result_id and r.teacher_id = (select auth.uid())));
create policy "result_answers_insert_owned_result" on public.result_answers for insert to authenticated
with check (exists (select 1 from public.results r where r.id = result_answers.result_id and r.teacher_id = (select auth.uid())));
create policy "result_answers_update_owned_result" on public.result_answers for update to authenticated
using (exists (select 1 from public.results r where r.id = result_answers.result_id and r.teacher_id = (select auth.uid())))
with check (exists (select 1 from public.results r where r.id = result_answers.result_id and r.teacher_id = (select auth.uid())));
create policy "result_answers_delete_owned_result" on public.result_answers for delete to authenticated
using (exists (select 1 from public.results r where r.id = result_answers.result_id and r.teacher_id = (select auth.uid())));

insert into storage.buckets (id, name, public)
values ('gradedock-scans','gradedock-scans',false)
on conflict (id) do nothing;

drop policy if exists "scan_objects_select_own" on storage.objects;
drop policy if exists "scan_objects_insert_own" on storage.objects;
drop policy if exists "scan_objects_update_own" on storage.objects;
drop policy if exists "scan_objects_delete_own" on storage.objects;

create policy "scan_objects_select_own" on storage.objects for select to authenticated
using (bucket_id='gradedock-scans' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "scan_objects_insert_own" on storage.objects for insert to authenticated
with check (bucket_id='gradedock-scans' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "scan_objects_update_own" on storage.objects for update to authenticated
using (bucket_id='gradedock-scans' and (storage.foldername(name))[1]=(select auth.uid())::text)
with check (bucket_id='gradedock-scans' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "scan_objects_delete_own" on storage.objects for delete to authenticated
using (bucket_id='gradedock-scans' and (storage.foldername(name))[1]=(select auth.uid())::text);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.classes, public.exams, public.exam_keys, public.results, public.result_answers to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- Class/exam archives and student roster (v3.20)
-- GradeDock v3.20 upgrade. Run ONCE in your EXISTING GradeDock Supabase SQL Editor.
-- Preserves all current classes, exams, keys, and scan results.
alter table public.classes add column if not exists is_archived boolean not null default false;
alter table public.exams add column if not exists is_archived boolean not null default false;

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references auth.users(id) on delete cascade,
  class_id uuid not null references public.classes(id) on delete cascade,
  full_name text not null check (length(trim(full_name)) > 0),
  gender text not null check (gender in ('Male', 'Female')),
  lrn text,
  created_at timestamptz not null default now()
);
create index if not exists gradedock_students_teacher_class_idx on public.students(teacher_id, class_id);
alter table public.students enable row level security;
drop policy if exists "gradedock_students_select" on public.students;
drop policy if exists "gradedock_students_insert" on public.students;
drop policy if exists "gradedock_students_update" on public.students;
drop policy if exists "gradedock_students_delete" on public.students;
create policy "gradedock_students_select" on public.students for select to authenticated
 using (teacher_id=(select auth.uid()) and exists (select 1 from public.classes c where c.id=students.class_id and c.teacher_id=(select auth.uid())));
create policy "gradedock_students_insert" on public.students for insert to authenticated
 with check (teacher_id=(select auth.uid()) and exists (select 1 from public.classes c where c.id=students.class_id and c.teacher_id=(select auth.uid())));
create policy "gradedock_students_update" on public.students for update to authenticated
 using (teacher_id=(select auth.uid()))
 with check (teacher_id=(select auth.uid()) and exists (select 1 from public.classes c where c.id=students.class_id and c.teacher_id=(select auth.uid())));
create policy "gradedock_students_delete" on public.students for delete to authenticated
 using (teacher_id=(select auth.uid()));
grant select,insert,update,delete on public.students to authenticated;

COMMIT;
